# Fine-Tuning Llama 3.1 8B using QLoRa for Healthcare Q&A - MedQuAD Dataset

###Jade Webb

###Jun 2026

###References:

###Dataset: https://www.kaggle.com/datasets/jpmiller/layoutlm

## Installations and Imports

In [18]:
import pandas as pd
from datasets import Dataset

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

##Load and Inspect MedQuAD Dataset

In [3]:
file_path = '/content/drive/MyDrive/Colab Notebooks/QLoRa/medquad.csv'

In [4]:
df = pd.read_csv(file_path)

In [5]:
df.head()

,question,answer,source,focus_area
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea...",NIHSeniorHealth,Glaucoma
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...,NIHSeniorHealth,Glaucoma
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ...",NIHSeniorHealth,Glaucoma
4,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16412 entries, 0 to 16411
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   question    16412 non-null  object
 1   answer      16407 non-null  object
 2   source      16412 non-null  object
 3   focus_area  16398 non-null  object
dtypes: object(4)
memory usage: 513.0+ KB

###Null

In [7]:
df = df.dropna(axis=0)

###Duplicates

In [8]:
df.duplicated().sum()

np.int64(48)

In [9]:
df = df.drop_duplicates()

### Irrelevant Columns

In [10]:
df = df.drop({"source", "focus_area"}, axis=1)

## Save Dataset

In [11]:
df.head()

,question,answer
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea..."
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ..."
4,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16345 entries, 0 to 16411
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   question  16345 non-null  object
 1   answer    16345 non-null  object
dtypes: object(2)
memory usage: 383.1+ KB

In [13]:
dataset = Dataset.from_pandas(df)

In [17]:
dataset.save_to_disk('/content/drive/MyDrive/Colab Notebooks/QLoRa/medquad_dataset')

Saving the dataset (0/1 shards):   0%|          | 0/16345 [00:00<?, ? examples/s]